# Generated by Django 5.1.6 on 2025-02-26 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('company_website', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('company_email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('company_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('first_payment', models.BooleanField(blank=True, default=False, null=True)),
                ('final_payment', models.BooleanField(blank=True, default=False, null=True)),
                ('kuwait', models.BooleanField(blank=True, default=False, null=True)),
                ('uae', models.BooleanField(blank=True, default=False, null=True)),
                ('qatar', models.BooleanField(blank=True, default=False, null=True)),
                ('saudi_arabia', models.BooleanField(blank=True, default=False, null=True)),
                ('oman', models.BooleanField(blank=True, default=False, null=True)),
                ('bahrain', models.BooleanField(blank=True, default=False, null=True)),
                ('south_africa', models.BooleanField(blank=True, default=False, null=True)),
                ('egypt', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
