# Generated by Django 5.1.6 on 2025-03-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_contact',
            new_name='person_contact',
        ),
        migrations.AddField(
            model_name='company',
            name='company_facebook',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_linkedin',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_twitter',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='person_email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='person_linked',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='person_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
