# Generated by Django 5.1.6 on 2025-03-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_rename_company_contact_company_person_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='negotiate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
